# Generated by Django 4.0 on 2021-12-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100)),
                ('article_author', models.CharField(max_length=100)),
                ('article_email', models.CharField(max_length=100)),
                ('artcle_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
