# Generated by Django 4.0 on 2021-12-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='artcle_date',
            new_name='article_date',
        ),
    ]
